### ISSUE TITLE
FR to add SNMPv3 support

### ISSUE THREAD

**Issue by Dunnenj** [gapitio/node-red-contrib-gapit-snmp#1]
Is it possible to add SNMPv3 support?

**Comment by sverre** [comment]
SNMPv3 support is planned, watch this space.

**Comment by Dunnenj** [comment]
> SNMPv3 support is planned, watch this space.

Great

**Comment by Dunnenj** [comment]
@sverre do you have an indication where this is on the roadmap?

**Comment by Dunnenj** [comment]
@sverre will you actively develop or is the development stopped?

**Comment by sverre** [comment]
Sorry about the lack of response. A version with SNMPv3 support should be out next week.

**Comment by Dunnenj** [comment]
That would be great. That will eliminate a security warning on my NAS.

**Comment by Dunnenj** [comment]
Thanks a lot. I can confirm that it is working and resolves a security warning.

**Comment by sverre** [comment]
Glad to hear it’s working.

If you have any general questions, rather than issues/feature requests, you can also tag me as @sverre over at the [Node-RED Forum](https://discourse.nodered.org/).
