### ISSUE TITLE
How to capture OID's type OctetString

### ISSUE THREAD

**Issue by Dunnenj** [gapitio/node-red-contrib-gapit-snmp#2]
Is it possible to capture Strings in case the OID returns an OctetString? In case this is possible how to do?

With the ultimate goal that the gapit-results-to-influx-batch Node processes it for injection in the Influx batch Node?

---
John

**Comment by sverre** [comment]
Missing string support is a bug, a fix is coming soon.

**Comment by Dunnenj** [comment]
Great to hear that this node is actively maintained.

**Comment by Dunnenj** [comment]
Fix is confirmed. Thanks.

**Comment by sverre** [comment]
Great! Sorry it took so long.
